export GIT_COMMITTER_NAME="SelfishPig"
export GIT_COMMITTER_EMAIL="none@none.com"
export GIT_AUTHOR_NAME="SelfishPig"
export GIT_AUTHOR_EMAIL="none@none.com"
export GIT_SSH_COMMAND="ssh -i /data/gitkey"
